name: CI
'on':
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.3.0
      - name: Install
        run: npm install
      - name: Run tests on Sauce Labs
        env:
          SAUCE_USERNAME: '${{ secrets.SAUCE_USERNAME }}'
          SAUCE_ACCESS_KEY: '${{ secrets.SAUCE_ACCESS_KEY }}'
        run: >-
          npx wdio config/wdio.android.sauce.conf.js --spec
          test/specs/android/add-note-screen.spec.js
      - name: Upload logs if failed
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs